JAS0NHUANG/ft_transcendence

backend/prisma/migrations/20230621095137_added_token_blacklist/migration.sql
backend/prisma/migrations/20230621112344_small_update/migration.sql
backend/prisma/migrations/20230621112544_small_update/migration.sql
backend/prisma/migrations/20230622115526_username_added_to_blacklist/migration.sql
backend/prisma/schema.prisma
backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/dto/update.dto.ts
backend/src/auth/strategy/TwoFA.strategy.ts
backend/src/auth/strategy/jwt.strategy.ts
backend/src/user/user.service.ts

Implemented logout strategy, and jwt token blacklist.

Auth amber

---

backend/src/auth/auth.service.ts
backend/src/socket/README.md

Just fix the 42 login bug. ^_^"

fix 42 login bug

---

App/README.md

Add a README file inside the APP directory. 
Summerize important notion in CSS : 
- Flexbox
- CSS grid
- Advanced accessors.

Frontend tiffany

---

App/src/App.tsx
App/src/components/LoginForm.tsx
App/src/pages/Hello.tsx
backend/src/game/game.service.ts
backend/src/socket/socket.gateway.ts

Tested very quickly. There are some connection-related bugs that I haven't quite figured out. But for now the invite functions seem to work fine. End game functions not tested yet.

invite functions done, not tested well yet

---

App/README.md
App/src/App.tsx
App/src/components/LoginForm.tsx
App/src/components/styles/README.md
App/src/pages/Hello.tsx
App/src/pages/Pong.tsx
backend/README.md
backend/src/auth/auth.service.ts
backend/src/dto/auth.dto.ts
backend/src/dto/game.dto.ts
backend/src/game/game.service.ts
backend/src/socket/README.md
backend/src/socket/socket.gateway.ts
backend/src/user/user.controller.ts
backend/src/user/user.service.ts

- save "player/client" in redis (in socket.gateway)
- add game logic.
still need some debug and testing 😃

Game redis

---

App/src/components/settings_components/CheckBox2FA.tsx
App/src/components/settings_components/EditAvatar.tsx
App/src/components/settings_components/SettingsPopUp.tsx
App/src/components/settings_components/styles/CheckBox2FA.styled.tsx
App/src/components/settings_components/styles/EditAvatar.styled.tsx
App/src/components/settings_components/styles/SettingsPopUp.styled.tsx
App/src/components/settings_components/styles/WhitePopUp.styled.tsx

Edit avatar working and improved css for settings page

Front edit avatar

---

backend/prisma/migrations/20230923144028_fix_friend_typo/migration.sql
backend/prisma/schema.prisma
backend/src/app.module.ts
backend/src/friend/friend.controller.spec.ts
backend/src/friend/friend.controller.ts
backend/src/friend/friend.module.ts
backend/src/friend/friend.service.spec.ts
backend/src/friend/friend.service.ts

- 3 simple GET requests for friend API. (using the getUser decorator).
- fix prisma typos.

Friend API GET requests

---

App/src/components/settings_components/EditAvatar.tsx

Edit Avatar issue: fixed

---

App/src/components/settings_components/CheckBox2FA.tsx
App/src/components/settings_components/EditPassword.tsx
App/src/components/settings_components/EditUsername.tsx
App/src/components/settings_components/SettingsPopUp.tsx
App/src/components/settings_components/styles/CheckBox2FA.styled.tsx
App/src/components/settings_components/styles/EditPassword.styled.tsx
App/src/components/settings_components/styles/EditUsername.styled.tsx
App/src/components/settings_components/styles/InputSettings.styled.tsx

Hidding Password when 42student

---

App/src/App.tsx
App/src/components/auth_components/LoginForm.tsx
App/src/components/auth_components/Modal2FA.tsx
App/src/components/auth_components/RegisterForm.tsx
App/src/pages/Authentification.tsx
App/src/pages/Register.tsx
App/src/pages/Verify2FA.tsx
backend/src/auth/auth.service.ts

- Separate page for 2FA after 42 auth 
- Save nonce into cookie, retrieve it then send request with the 6 digit code
- Redirect to frontend "/settings" if the user login for the first time via 42 auth (as mentioned in the subject)

69 auth 42 api href to request

---

App/src/components/landing_components/AvatarBar.tsx
App/src/components/landing_components/NavBar.tsx

Logout is now working and remove auth cookie

68 enable logout

---

App/src/components/landing_components/styles/AvatarBar.styled.tsx
App/src/pages/Pong.tsx
App/src/theme/GlobalStyle.tsx

- add `<Landing>` component into Pong.tsx page.
- Some minor styling changes.

Pong.tsx as a Page

---

backend/src/auth/auth.controller.spec.ts
backend/src/chat/chat.service.ts
backend/src/chat/chat.socket.gateway.ts
backend/src/dto/chat.dto.ts
backend/src/game/game.service.spec.ts
backend/src/socket/game.socket.gateway.ts

Logic for direct messaging:
- Expected from client: event `createChannel`, payload `name: username, status: DIRECT`
- Some checks are performed 
- A room is created with the 2 users connected
- The cache is updated for current user, and for the other user if possible
- Socket of current user is joined
- Server emits to other user: `reconnectNeeded`, message `Please reconnect chat websocket`
- Upon reconnect, the other user will be joined to the room

53 chat write the logic for direct messaging

---

backend/src/chat/README.md
backend/src/chat/chat.controller.ts
backend/src/chat/chat.module.ts
backend/src/chat/chat.service.ts
backend/src/chat/chat.socket.gateway.ts
backend/src/socket/README.md

Small pull request in order to create chat landing page

90 chat info landing chat

---

App/src/App.tsx
App/src/components/auth_components/LoginForm.tsx
App/src/components/auth_components/Modal2FA.tsx
App/src/components/auth_components/RegisterForm.tsx
App/src/components/landing_components/NavBar.tsx
App/src/pages/Verify2FA.tsx
backend/src/auth/auth.service.ts

Backend:
I only change the 42 login redirections to "/landing".

95 routing change landing path

---

backend/src/dto/user.dto.ts
backend/src/friend/friend.service.ts
backend/src/user/user.service.ts

- add "achievements" in secureUser dto
- update returned value in related API

Achievements for secureUser

---

App/src/components/friends_components/FriendsList.tsx
App/src/components/friends_components/styles/FriendsList.styled.tsx
App/src/components/profile_components/styles/ProfileAvatar.styled.tsx

Updated the color of user status in friend page depending on the status

update status color for friend page

---

backend/prisma/schema.prisma
backend/src/socket/game.socket.gateway.ts

- Two simple bug fix.
- remove some unused import

Fix Achievements Unique constraint, Remove the Double endGame

---

backend/src/friend/friend.controller.ts
backend/src/friend/friend.service.ts

- unfriend by username.
- FRIEND achievement is added

unfriend by username, FRIEND achievement added

---

App/src/pages/Verify2FA.tsx

Fix redirection after signing in with 42 Api if 2FA is enable ti navigate to "/landing".

[AUTH - 2FA] - Redirection after sign in 2FA with 42 Api

---

App/src/components/styles/PagesContainer.styled.tsx

Just overflow hidden remove ; it should not cause problem with the rest, if it's the case please notify so I can patch problem

little change to avoid overflow hidden

---

App/src/components/chat_components/Conversation_components/ConversationMenu.tsx
App/src/components/chat_components/Conversation_components/ConversationUsersListModal.tsx
App/src/components/chat_components/Conversation_components/styles/ConversationHeader.styled.tsx
App/src/components/chat_components/Conversation_components/styles/ConversationMenu.styled.tsx
App/src/components/chat_components/Conversation_components/styles/ConversationSettingsModal.styled.tsx
App/src/components/chat_components/Conversation_components/styles/ConversationUsersListModal.styled.tsx
App/src/components/chat_components/Conversation_components/styles/ConversationWindow.styled.tsx
App/src/components/chat_components/NewChat_components/NewChatModal.tsx
App/src/components/chat_components/styles/ChatNavigation.styled.tsx
App/src/components/chat_components/styles/ChatWrapper.styled.tsx
App/src/components/chat_components/styles/UserChatList.styled.tsx

Button Channel Settings Improve
Chat Page Responsive 
Modals for Channel Settings as Portal
Styled Channel Setting improve

143 chat front improve setting button display responsive + adapt on user chan role

---

App/src/components/chat_components/Conversation_components/ConversationSettingsModal.tsx
App/src/components/chat_components/Conversation_components/styles/ConversationSettingsModal.styled.tsx

Channel Status : Private <-> Public can be changed by front
Also we cannot set a channel to private without specifying a password

152 chat add front resquest for update channel status private public

---

backend/prisma/migrations/20231007090148_removing_is_blocked/migration.sql
backend/prisma/schema.prisma
backend/src/channel/channel.service.ts
backend/src/chat/chat.service.ts
backend/src/dto/chat.dto.ts
backend/src/game/game.service.ts
backend/src/socket/game.socket.gateway.ts

Return roles in channel
Make banned users appear in the channel member list
No special characters in room names

167 chat return channel roles

---

backend/src/chat/chat.service.ts
backend/src/dto/user.dto.ts
backend/src/game/game.module.ts
backend/src/game/game.service.ts
backend/src/socket/socket.module.ts
backend/src/user/user.service.ts

Normally all 5 achievements should be added correctly now.
(To be tested!)

169 achievements make twofa join first work

---

backend/src/chat/chat.service.ts
backend/src/dto/chat.dto.ts
backend/src/game/game.module.ts
backend/src/game/game.service.ts
backend/src/socket/game.socket.gateway.ts
backend/src/user/user.service.ts

Since validation pipes don't work on socket.io input, I added an extra step to verify if no extra info is being injected in the createRoom event.

173 chat test and protect socket input

---

App/src/components/profile_components/ProfileAvatar.tsx
App/src/components/profile_components/styles/ProfileAvatar.styled.tsx

180 block | unblock users from profile page

---

backend/src/game/game.service.ts
backend/src/game/retro.game.service.ts
backend/src/socket/game.socket.gateway.ts

Remove most of the console log in game.service and game.socket

remove some console log in game

---

App/src/components/settings_components/EditUsername.tsx
backend/src/auth/auth.service.ts
backend/src/game/game.service.ts
backend/src/user/user.service.ts

fix catch and throw 500 error in updated settings

[500 ERROR] Try catch
